arcus-azure/arcus.backgroundjobs

docs/preview/features/cloudevent/receive-cloudevents-job.md
docs/preview/features/security/auto-invalidate-secrets.md
docs/preview/index.md
docs/v0.1/features/cloudevent/receive-cloudevents-job.md
docs/v0.1/features/security/auto-invalidate-secrets.md
docs/v0.1/index.md

* All the docs are marked with a version since when it's available
* All the docs are split onto changes for each full release
* The "currenly available, but not yet released" features have been split into the `preview` folder
* The `./docs/features` folder contains now the available features of the most recent version (inclusive the preview releases)
Relates to https://github.com/arcus-azure/arcus/issues/75

Docs - split docs on feature changes on each full release

---

build/nuget-release.yml

YAML NuGet release stage wasn't dependent on the unit tests stage.

Fix - release should be dependent on unit tests

---

build/ci-build.yml
build/nuget-release.yml
build/variables/test.yml
src/Arcus.BackgroundJobs.Tests.Integration/Jobs/AutoInvalidateKeyVaultSecretJobTests.cs
src/Arcus.BackgroundJobs.Tests.Integration/Jobs/DatabricksJobMetricsJobTests.cs
src/Arcus.BackgroundJobs.Tests.Integration/appsettings.json

Since we now have access to a Databricks cluster on Azure, we can use it to run our Databricks integration tests.

Testing - activate Databricks background jobs integration test

---

docs/features/cloudevent/receive-cloudevents-job.md
docs/features/databricks/gain-insights.md
docs/features/databricks/job-metrics.md
docs/features/security/auto-invalidate-secrets.md
docs/preview/features/cloudevent/receive-cloudevents-job.md
docs/preview/features/databricks/gain-insights.md
docs/preview/features/databricks/job-metrics.md
docs/preview/features/security/auto-invalidate-secrets.md
docs/v0.1/features/cloudevent/receive-cloudevents-job.md
docs/v0.1/features/security/auto-invalidate-secrets.md
docs/v0.2/features/cloudevent/receive-cloudevents-job.md
docs/v0.2/features/databricks/gain-insights.md
docs/v0.2/features/databricks/job-metrics.md
docs/v0.2/features/security/auto-invalidate-secrets.md

Add missing `using' statements to the feature docs.
Relates to https://github.com/arcus-azure/arcus/issues/107

Docs - add missing 'using's to the feature docs

---

src/Arcus.BackgroundJobs.CloudEvents/Arcus.BackgroundJobs.CloudEvents.csproj
src/Arcus.BackgroundJobs.Databricks/Arcus.BackgroundJobs.Databricks.csproj
src/Arcus.BackgroundJobs.KeyVault/Arcus.BackgroundJobs.KeyVault.csproj

Let's use package version ranges to make the Arcus package dependencies more stable.
Relates to https://github.com/arcus-azure/arcus/issues/129

feat: use package version ranges for Arcus dependencies

---

build/ci-build.yml
build/nuget-release.yml
docs/preview/features/security/auto-restart-servicebus-messagepump-on-rotated-credentials.md
docs/preview/index.md
src/Arcus.BackgroundJobs.KeyVault/Arcus.BackgroundJobs.KeyVault.csproj
src/Arcus.BackgroundJobs.KeyVault/Extensions/IServiceCollectionExtensions.cs
src/Arcus.BackgroundJobs.KeyVault/ReAuthenticateOnRotatedCredentialsMessageHandler.cs
src/Arcus.BackgroundJobs.Tests.Integration/Arcus.BackgroundJobs.Tests.Integration.csproj
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/KeyVault/KeyRotationConfig.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/KeyVault/KeyVaultConfig.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/KeyVault/KeyVaultEventEndpoint.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/ServiceBus/Customer.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/ServiceBus/Order.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/ServiceBus/OrderCreatedEventData.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/ServiceBus/OrdersAzureServiceBusMessageHandler.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/ServiceBus/ServiceBusConfiguration.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/ServiceBus/ServiceBusNamespace.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/ServicePrincipal.cs
src/Arcus.BackgroundJobs.Tests.Integration/Hosting/ServiceBus/TestMessagePumpService.cs
src/Arcus.BackgroundJobs.Tests.Integration/Hosting/TestConfig.cs
src/Arcus.BackgroundJobs.Tests.Integration/Hosting/Worker.cs
src/Arcus.BackgroundJobs.Tests.Integration/Hosting/WorkerOptions.cs
src/Arcus.BackgroundJobs.Tests.Integration/Jobs/AutoRestartServiceBusMessagePumpOnRotatedCredentialsJobTests.cs
src/Arcus.BackgroundJobs.Tests.Integration/appsettings.json
src/Arcus.BackgroundJobs.Tests.Unit/Arcus.BackgroundJobs.Tests.Unit.csproj
src/Arcus.BackgroundJobs.Tests.Unit/Blanks.cs
src/Arcus.BackgroundJobs.Tests.Unit/KeyVault/IServiceCollectionExtensionsTests.cs

Moves the Azure Service Bus auto-restart on rotated credentials functionality from the messaging repo to here, as it's a background job.
Closes #69

feat: move auto-restart az servicebus message pump on rotated credentials

---

src/Arcus.BackgroundJobs.CloudEvents/Arcus.BackgroundJobs.CloudEvents.csproj
src/Arcus.BackgroundJobs.CloudEvents/Extensions/IServiceCollectionExtensions.cs
src/Arcus.BackgroundJobs.KeyVault/Arcus.BackgroundJobs.KeyVault.csproj
src/Arcus.BackgroundJobs.Tests.Integration/CloudEvents/CloudEventBackgroundJobTests.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/ServiceBus/OrderGenerator.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/ServiceBus/OrderV2.cs
src/Arcus.BackgroundJobs.Tests.Integration/Fixture/ServiceBus/OrdersV2AzureServiceBusMessageHandler.cs
src/Arcus.BackgroundJobs.Tests.Integration/Hosting/ServiceBus/TestMessagePumpService.cs

Provide the message pump/background job messaging options via the CloudEvents extensions.
Relates to https://github.com/arcus-azure/arcus.backgroundjobs/pull/74

feat: configurable messaging options in cloudevents background job

---

README.md

Add the newly added project for Azure Active Directory background jobs to the README file.
Closes #97

docs: add Azure Active Directory background jobs to README

---

docs/README.md

We should mention in the feature documentation to use a recent version of `npm`, as older versions gave errors.
Relates to https://github.com/arcus-azure/arcus/issues/155

docs: mention to use a recent `npm` version

---

src/Arcus.BackgroundJobs.KeyVault/Extensions/IServiceCollectionExtensions.cs
src/Arcus.BackgroundJobs.Tests.Integration/KeyVault/AutoRestartServiceBusMessagePumpOnRotatedCredentialsJobTests.cs
src/Arcus.BackgroundJobs.Tests.Unit/KeyVault/IServiceCollectionExtensionsTests.cs

Make the auto restart Azure Service Bus message pump on Azure Key Vault secrets a configurable background job.
Closes #82

feat: make az keyvault background jobs configurable

---

docs/preview/02-Features/02-Security/auto-restart-servicebus-messagepump-on-rotated-credentials.md
src/Arcus.BackgroundJobs.AzureActiveDirectory/Arcus.BackgroundJobs.AzureActiveDirectory.csproj
src/Arcus.BackgroundJobs.KeyVault/Extensions/IServiceCollectionExtensions.cs
src/Arcus.BackgroundJobs.KeyVault/Extensions/ServiceBusMessageHandlerCollectionExtensions.cs
src/Arcus.BackgroundJobs.Tests.Integration/KeyVault/AutoRestartServiceBusMessagePumpOnRotatedCredentialsJobTests.cs
src/Arcus.BackgroundJobs.Tests.Unit/KeyVault/IServiceCollectionExtensionsTests.cs
src/Arcus.BackgroundJobs.Tests.Unit/KeyVault/ServiceCollectionExtensionsTests.cs

Adds dedicated extension for the adding of the auto-restart message pump on rotated Azure Key Vault credentials.
Closes #109

fix: add dedicated auto restart extension

---

src/Arcus.BackgroundJobs.AzureActiveDirectory/Arcus.BackgroundJobs.AzureActiveDirectory.csproj
src/Arcus.BackgroundJobs.AzureAppConfiguration/Arcus.BackgroundJobs.AzureAppConfiguration.csproj
src/Arcus.BackgroundJobs.CloudEvents/Arcus.BackgroundJobs.CloudEvents.csproj
src/Arcus.BackgroundJobs.Databricks/Arcus.BackgroundJobs.Databricks.csproj
src/Arcus.BackgroundJobs.KeyVault/Arcus.BackgroundJobs.KeyVault.csproj

Adds the GitHub README file to the NuGet package generation of the projects.
Adds feature docs project URL instead of GitHub URL to NuGet package.
Relates to arcus-azure/arcus#209
Relates to arcus-azure/arcus#208

chore: add readme and proj url to nuget pkg

---

src/Arcus.BackgroundJobs.AzureActiveDirectory/ClientSecretExpirationJob.cs
src/Arcus.BackgroundJobs.AzureActiveDirectory/Extensions/IServiceCollectionExtensions.cs
src/Arcus.BackgroundJobs.Databricks/DatabricksJobMetricsJob.cs
src/Arcus.BackgroundJobs.Databricks/Extensions/IServiceCollectionExtensions.cs

Remove the attempt to log on unobserved exceptions.
We tried to retrieve back the registered logging system, but this is not only wrong, it is rather unstable.
We can either remove this, like in this PR, so that the consumers can see directly what's wrong with their scheduled job (authentication, processing failures...)
Or we can come up with a more resilient scheduled job that logs critical errors for unhandled exceptions in the scheduled job instead on relying on the incomplete 'unobsered exception handling'.
See also https://github.com/kdcllc/CronScheduler.AspNetCore/issues/47 and https://github.com/kdcllc/CronScheduler.AspNetCore/pull/48

fix: remove invalid exn handling

---

src/Arcus.BackgroundJobs.CloudEvents/CloudEventBackgroundJobOptions.cs

Since we now use the message router to handle deserialization, there's no need for a dedicated message pump for the CloudEvents background jobs, and therefore, no need for a dedicated set of options. These options were not removed during this migration because of backwards-compatibility, but should be marked as deprecated.

chore: mark unnecessary cloudevents options as obsolete

---

src/Arcus.BackgroundJobs.AzureActiveDirectory/ClientSecretExpirationJobOptions.cs
src/Arcus.BackgroundJobs.AzureActiveDirectory/Extensions/IServiceCollectionExtensions.cs
src/Arcus.BackgroundJobs.AzureAppConfiguration/Extensions/IServiceCollectionExtensions.cs
src/Arcus.BackgroundJobs.CloudEvents/Extensions/IServiceCollectionExtensions.cs
src/Arcus.BackgroundJobs.Databricks/DatabricksJobMetricsJobSchedulerOptions.cs
src/Arcus.BackgroundJobs.Databricks/Extensions/IServiceCollectionExtensions.cs
src/Arcus.BackgroundJobs.KeyVault/Extensions/IServiceCollectionExtensions.cs
src/Arcus.BackgroundJobs.KeyVault/Extensions/ServiceBusMessageHandlerCollectionExtensions.cs

Adds code XML `<remarks/>` to explain dependent Arcus services and show a simular help message when those services aren't there when the job is initialized.
Closes #140

feat: add `<remarks/>` and descriptive exceptions on job registrations

---

README.md

Since the background job is not available now, but will be once we release the feature docs, we should make sure that the updated README is part of the NuGet packages.

chore: update readme with future available job

---

deploy/bicep/app-config-keyvalue-change-event-subcription-to-servicebus-topic.bicep

Because the 'Deploy to Azure' button requires a raw GitHub URL, we can't add it yet as it isn't present yet on `master`.

docs: add app config bicep template

---

docs/preview/02-Features/05-AzureAppConfiguration/auto-refresh-app-configuration.md
src/Arcus.BackgroundJobs.AzureAppConfiguration/Extensions/IServiceCollectionExtensions.cs
src/Arcus.BackgroundJobs.Tests.Integration/AppConfiguration/AutoRefreshAppConfigurationBackgroundJobTests.cs
src/Arcus.BackgroundJobs.Tests.Unit/AppConfiguration/IServiceCollectionExtensionsTests.cs

Add managed identity support for the Azure App Configuration background job that auto-refreshes the application configuration.
Closes #156

feat: add managed identity support auto-refresh app config job

---

build/ci-build.yml

Use `main` branch in CI build trigger.
Relates to https://github.com/arcus-azure/arcus/issues/169

chore: update CI build to `main`

---

docs/preview/01-index.md
docs/versioned_docs/version-v0.4.0/01-index.md

Add introduction section to the feature documentation on both the most recent published docs v0.4 as the preview feature docs.

docs: add introduction section

---

README.md

Use the default `main` branch in the `README.md` icon.

chore: use main branch readme icon
